name: Track and notify updates

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

# Grant "Read and write permissions" to actions from:
# https://github.com/ras0q/kaggle-leaderboard-updates/settings/actions
permissions:
  contents: write
  issues: write

env:
  KAGGLE_COMPETITION: "titanic" # CHANGE THIS!!!
  ISSUE_TITLE: "Leaderboard Update"

# Required secrets
# - KAGGLE_USERNAME
# - KAGGLE_KEY

jobs:
  check-leaderboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install .
      - name: Setup Kaggle API
        run: |
          mkdir -p ~/.kaggle
          cat <<EOF > ~/.kaggle/kaggle.json
          {
            "username": "${{ secrets.KAGGLE_USERNAME }}",
            "key": "${{ secrets.KAGGLE_KEY }}",
            "competition": "${{ env.KAGGLE_COMPETITION }}"
          }
          EOF
          chmod 600 ~/.kaggle/kaggle.json
      - name: Fetch leaderboard
        run: kaggle competitions leaderboard --csv --show --quiet > new_leaderboard.csv 2>&1
      - name: Compare with previous leaderboard
        run: |
          if [ -f leaderboard.csv ]; then
            python ./src/compare_leaderboard.py leaderboard.csv new_leaderboard.csv > rank_changes.txt 2>&1
          fi
      - name: Update leaderboard file
        run: |
          mv new_leaderboard.csv leaderboard.csv
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add leaderboard.csv
          git commit -m "Update leaderboard data" || echo "No changes to commit"
          git push || echo "No changes to push"
      - name: Notify via GitHub Issue
        run: |
          if [ -s rank_changes.txt ]; then
            ISSUE_NUMBER=$(gh issue list --state open --search "$ISSUE_TITLE" --limit 1 --json number --jq '.[0].number')
            if [ -z "$ISSUE_NUMBER" ]; then
              gh issue create --title "$ISSUE_TITLE" --body ""
            fi
            gh issue comment $ISSUE_NUMBER -F rank_changes.txt
          fi
